import type { MenuItem } from "@/Model";

export const mockedData: MenuItem[] = [
  {
    id: 1,
    nombre: "Ristretto",
    categoria: "CAFETERIA",
    descripcion: "",
    description: "",
    precio: 3500,
    vegetariano: false,
    sinTacc: false,
    onOff: true,
  },
  {
    id: 2,
    nombre: "Cafe corto",
    categoria: "CAFETERIA",
    descripcion: "",
    description: "",
    precio: 3500,
    vegetariano: false,
    sinTacc: false,
    onOff: false,
  },
  {
    id: null,
    nombre: "Jarrita",
    categoria: "CAFETERIA",
    descripcion: "",
    description: "",
    precio: 4000,
    vegetariano: false,
    sinTacc: false,
    onOff: null,
  },
  {
    id: 3,
    nombre: "Cafe doble",
    categoria: "CAFETERIA",
    descripcion: "",
    description: "",
    precio: 4500,
    vegetariano: false,
    sinTacc: false,
    onOff: null,
  },
  {
    id: 4,
    nombre: "Cafe con leche",
    categoria: "CAFETERIA",
    descripcion: "",
    description: "",
    precio: 4500,
    vegetariano: false,
    sinTacc: false,
    onOff: null,
  },
  {
    id: 5,
    nombre: "Cortado corto",
    categoria: "CAFETERIA",
    descripcion: "",
    description: "",
    precio: 3500,
    vegetariano: false,
    sinTacc: false,
    onOff: null,
  },
  {
    id: null,
    nombre: "Cortado Jarrita",
    categoria: "CAFETERIA",
    descripcion: "",
    description: "",
    precio: null,
    vegetariano: false,
    sinTacc: false,
    onOff: null,
  },
  {
    id: 6,
    nombre: "Cortado doble",
    categoria: "CAFETERIA",
    descripcion: "",
    description: "",
    precio: 4500,
    vegetariano: false,
    sinTacc: false,
    onOff: null,
  },
  {
    id: 7,
    nombre: "Lagrima",
    categoria: "CAFETERIA",
    descripcion: "",
    description: "",
    precio: 4500,
    vegetariano: false,
    sinTacc: false,
    onOff: null,
  },
  {
    id: 8,
    nombre: "Capuccino",
    categoria: "CAFETERIA",
    descripcion: "",
    description: "",
    precio: 6000,
    vegetariano: false,
    sinTacc: false,
    onOff: null,
  },
  {
    id: 9,
    nombre: "Submarino",
    categoria: "CAFETERIA",
    descripcion: "",
    description: "",
    precio: 6000,
    vegetariano: false,
    sinTacc: false,
    onOff: null,
  },
  {
    id: 10,
    nombre: "Chocolatada",
    categoria: "CAFETERIA",
    descripcion: "",
    description: "",
    precio: 6000,
    vegetariano: false,
    sinTacc: false,
    onOff: null,
  },
  {
    id: 11,
    nombre: "Te",
    categoria: "CAFETERIA",
    descripcion: "",
    description: "",
    precio: 3500,
    vegetariano: false,
    sinTacc: false,
    onOff: null,
  },
  {
    id: 12,
    nombre: "Mate cocido",
    categoria: "CAFETERIA",
    descripcion: "",
    description: "",
    precio: 3500,
    vegetariano: false,
    sinTacc: false,
    onOff: null,
  },
  {
    id: 13,
    nombre: "Licuados",
    categoria: "CAFETERIA",
    descripcion: "",
    description: "",
    precio: 6000,
    vegetariano: false,
    sinTacc: false,
    onOff: null,
  },
  {
    id: 14,
    nombre: "Tostados de jamon y queso",
    categoria: "CAFETERIA",
    descripcion: "",
    description: "",
    precio: 6500,
    vegetariano: false,
    sinTacc: false,
    onOff: null,
  },
  {
    id: 15,
    nombre: "Tanda de pan de campo",
    categoria: "CAFETERIA",
    descripcion:
      "Tanda de bollo casero (pan de campo artesanal) acompañado de queso de cabra local y dulce de cayote.",
    description:
      "A selection of our rustic, artisan country rolls served warm, paired with locally crafted goat cheese and traditional cayote preserve.",
    precio: 5000,
    vegetariano: false,
    sinTacc: false,
    onOff: null,
  },
  {
    id: 16,
    nombre: "Alfajor de maicena",
    categoria: "CAFETERIA",
    descripcion:
      "Masa de almidón de maíz, dulce de leche y coco.",
    description:
      "A delicate cornstarch dough filled with silky dulce de leche and finished with shredded coconut.",
    precio: 3000,
    vegetariano: false,
    sinTacc: false,
    onOff: null,
  },
  {
    id: 17,
    nombre: "Pastafrola",
    categoria: "CAFETERIA",
    descripcion:
      "Masa quebrada y dulce de membrillo artesanal.",
    description:
      "Buttery, crumbly shortcrust filled with handcrafted quince jam, a timeless Argentine classic.",
    precio: 3000,
    vegetariano: false,
    sinTacc: false,
    onOff: null,
  },
  {
    id: 18,
    nombre: "Alfajor de maiz andino",
    categoria: "CAFETERIA",
    descripcion:
      "Alfajores artesanales libres de gluten. Elige entre masa de maíz capia o maíz morado, ambos rellenos con dulce de leche.",
    description:
      "Choose between capia corn or purple corn dough, both generously filled with smooth dulce de leche.",
    precio: 3000,
    vegetariano: false,
    sinTacc: true,
    onOff: null,
  },
  {
    id: 19,
    nombre: "Empanadilla",
    categoria: "CAFETERIA",
    descripcion:
      "Pequeña empanada dulce artesanal, rellena de dulce de cayote regional y terminada con un suave glase de azúcar.",
    description:
      "A small handmade pastry filled with regional cayote preserve and finished with a light sugar glaze.",
    precio: 2500,
    vegetariano: false,
    sinTacc: false,
    onOff: null,
  },
  {
    id: 20,
    nombre: "Cabsha",
    categoria: "CAFETERIA",
    descripcion:
      "Tarta individual de chocolate con corazón de dulce de leche y baño de chocolate.",
    description:
      "Rich chocolate tart with a molten dulce de leche center, coated in a smooth chocolate glaze.",
    precio: 3000,
    vegetariano: false,
    sinTacc: false,
    onOff: null,
  },
  {
    id: 22,
    nombre: "Cafe para llevar",
    categoria: "CAFETERIA",
    descripcion: "",
    description: "",
    precio: 5500,
    vegetariano: false,
    sinTacc: false,
    onOff: null,
  },
  {
    id: 23,
    nombre: "Coca Cola",
    categoria: "BEBIDA",
    descripcion: "",
    description: "",
    precio: 3500,
    vegetariano: false,
    sinTacc: false,
    onOff: null,
  },
  {
    id: 24,
    nombre: "Coca Cola Zero",
    categoria: "BEBIDA",
    descripcion: "",
    description: "",
    precio: 3500,
    vegetariano: false,
    sinTacc: false,
    onOff: null,
  },
  {
    id: 25,
    nombre: "Sprite",
    categoria: "BEBIDA",
    descripcion: "",
    description: "",
    precio: 3500,
    vegetariano: false,
    sinTacc: false,
    onOff: null,
  },
  {
    id: 26,
    nombre: "Fanta",
    categoria: "BEBIDA",
    descripcion: "",
    description: "",
    precio: 3500,
    vegetariano: false,
    sinTacc: false,
    onOff: null,
  },
  {
    id: 27,
    nombre: "Aquarius",
    categoria: "BEBIDA",
    descripcion: "",
    description: "",
    precio: 3500,
    vegetariano: false,
    sinTacc: false,
    onOff: null,
  },
  {
    id: 28,
    nombre: "Agua con gas",
    categoria: "BEBIDA",
    descripcion: "",
    description: "",
    precio: 3000,
    vegetariano: false,
    sinTacc: false,
    onOff: null,
  },
  {
    id: 29,
    nombre: "Agua sin gas",
    categoria: "BEBIDA",
    descripcion: "",
    description: "",
    precio: 3000,
    vegetariano: false,
    sinTacc: false,
    onOff: null,
  },
  {
    id: 30,
    nombre: "Limonada",
    categoria: "BEBIDA",
    descripcion: "",
    description: "",
    precio: 3500,
    vegetariano: false,
    sinTacc: false,
    onOff: null,
  },
  {
    id: 31,
    nombre: "Pomelada",
    categoria: "BEBIDA",
    descripcion: "",
    description: "",
    precio: 3500,
    vegetariano: false,
    sinTacc: false,
    onOff: null,
  },
  {
    id: 32,
    nombre: "Jugo de naranja",
    categoria: "BEBIDA",
    descripcion: "",
    description: "",
    precio: 5500,
    vegetariano: false,
    sinTacc: false,
    onOff: null,
  },
  {
    id: 33,
    nombre: "Cerveza Salta rubia 500ml",
    categoria: "BEBIDA",
    descripcion: "",
    description: "",
    precio: 600,
    vegetariano: false,
    sinTacc: false,
    onOff: null,
  },
  {
    id: 34,
    nombre: "Cerveza Salta negra 500ml",
    categoria: "BEBIDA",
    descripcion: "",
    description: "",
    precio: 6000,
    vegetariano: false,
    sinTacc: false,
    onOff: null,
  },
  {
    id: 35,
    nombre: "Cerveza Salta 1lt",
    categoria: "BEBIDA",
    descripcion: "",
    description: "",
    precio: 9000,
    vegetariano: false,
    sinTacc: false,
    onOff: null,
  },
  {
    id: 36,
    nombre: "Copa de vino Malbec",
    categoria: "BEBIDA",
    descripcion: "",
    description: "",
    precio: 6000,
    vegetariano: false,
    sinTacc: false,
    onOff: null,
  },
  {
    id: 37,
    nombre: "Vino Don Pedro",
    categoria: "BEBIDA",
    descripcion: "",
    description: "",
    precio: 11000,
    vegetariano: false,
    sinTacc: false,
    onOff: null,
  },
  {
    id: 38,
    nombre: "Vino El Secreto",
    categoria: "BEBIDA",
    descripcion: "",
    description: "",
    precio: 12000,
    vegetariano: false,
    sinTacc: false,
    onOff: null,
  },
  {
    id: 39,
    nombre: "Vino Finca Las Curtiembres",
    categoria: "BEBIDA",
    descripcion: "",
    description: "",
    precio: 15000,
    vegetariano: false,
    sinTacc: false,
    onOff: null,
  },
  {
    id: 40,
    nombre: "Vino Valentin Ramirez",
    categoria: "BEBIDA",
    descripcion: "",
    description: "",
    precio: 20000,
    vegetariano: false,
    sinTacc: false,
    onOff: null,
  },
  {
    id: 41,
    nombre: "Tamal",
    categoria: "REGIONAL",
    descripcion:
      "Pequeña bola artesanal de masa de maíz rellena de carne vacuna mechada, envuelta en su propia chala natural.",
    description:
      "A small handmade corn dough parcel filled with shredded beef, wrapped and steamed in its natural husk.",
    precio: 5000,
    vegetariano: false,
    sinTacc: true,
    onOff: null,
  },
  {
    id: 42,
    nombre: "Humita en chala",
    categoria: "REGIONAL",
    descripcion:
      "Choclo fresco rallado, zapallo y queso, envuelto para su cocción en la propia hoja natural (chala).",
    description:
      "Grated sweet corn blended with pumpkin and cheese, delicately wrapped in its own husk and gently steamed.",
    precio: null,
    vegetariano: true,
    sinTacc: true,
    onOff: null,
  },
  {
    id: 43,
    nombre: "Humita a la olla",
    categoria: "REGIONAL",
    descripcion:
      "Sopa cremosa artesanal de choclo fresco y calabaza, servida sobre un colchón de queso de cabra artesanal de nuestra quebrada.",
    description:
      "A velvety artisan soup made from fresh corn and pumpkin, served over a bed of locally crafted goat cheese from our valley.",
    precio: 15000,
    vegetariano: true,
    sinTacc: true,
    onOff: null,
  },
  {
    id: 44,
    nombre: "Locro",
    categoria: "REGIONAL",
    descripcion:
      "El plato nacional de Argentina. Un guisado a base de zapallo criollo, maíz, porotos, carne vacuna y embutidos, cocinado en olladas a fuego lento.",
    description:
      "Our country's iconic dish: a slow-simmered stew of criollo squash, corn, beans, beef, and traditional sausages, cooked in large pots over a gentle flame.",
    precio: 16000,
    vegetariano: false,
    sinTacc: true,
    onOff: null,
  },
  {
    id: 45,
    nombre: "Frangollo",
    categoria: "REGIONAL",
    descripcion:
      "Plato ansestral de maíz blanco de altura trozado en mortero. Cocción lenta con carne vacuna y vegetales, logrando una sopa cremosa y espesa.",
    description:
      "High-altitude white corn, stone-crushed in a mortar and slow-cooked with beef and vegetables, resulting in a rich, creamy, and hearty soup.",
    precio: 15000,
    vegetariano: false,
    sinTacc: true,
    onOff: null,
  },
  {
    id: 46,
    nombre: "Cazuela de cabrito",
    categoria: "REGIONAL",
    descripcion:
      "Estofado de cocción lenta con carne de cabrito de los Valles Calchaquíes, acompañada de trozos rústicos de papa, zanahoria, arvejas y pimientos seleccionados.",
    description:
      "Tender kid goat from the Calchaquí Valleys, slowly simmered and served with rustic chunks of potato, carrot, peas, and hand-selected peppers.",
    precio: 16000,
    vegetariano: false,
    sinTacc: true,
    onOff: null,
  },
  {
    id: null,
    nombre: "Provoleta de Cabra",
    categoria: "REGIONAL",
    descripcion:
      "Queso de cabra de producción local a la plancha, dorado y cremoso. Incluye guarnición de papas rústicas o ensalada clásica.",
    description:
      "Locally produced goat cheese, golden and creamy from the grill. Served with rustic potatoes or a classic salad.",
    precio: null,
    vegetariano: true,
    sinTacc: true,
    onOff: null,
  },
  {
    id: 47,
    nombre: "Milanesa sola",
    categoria: "CARNES",
    descripcion:
      "Filet de carne vacuna rebozada artesanalmente. Incluye guarnición de papas rústicas o ensalada.",
    description:
      "Hand-breaded beef cutlet, served with rustic potatoes or a classic salad.",
    precio: 15500,
    vegetariano: false,
    sinTacc: false,
    onOff: null,
  },
  {
    id: 48,
    nombre: "Milanesa a caballo",
    categoria: "CARNES",
    descripcion:
      "Milanesa de carne vacuna con dos huevos fritos arriba. Incluye guarnición de papas rústicas o ensalada clásica.",
    description:
      "Traditional breaded beef topped with two fried eggs. Served with rustic potatoes or a classic salad.",
    precio: 17000,
    vegetariano: false,
    sinTacc: false,
    onOff: null,
  },
  {
    id: 49,
    nombre: "Milanesa Alemania",
    categoria: "CARNES",
    descripcion:
      "(Plato de la Casa) Milanesa de carne vacuna cubierta con salsa artesanal y queso de cabra regional gratinado. Acompañada de papas rústicas o ensalada clásica.",
    description:
      "Breaded beef cutlet topped with our homemade sauce and regional goat cheese, melted to perfection. Served with rustic potatoes or a classic salad.",
    precio: 17000,
    vegetariano: false,
    sinTacc: false,
    onOff: null,
  },
  {
    id: 50,
    nombre: "Milanesa a la fugazzeta",
    categoria: "CARNES",
    descripcion:
      "Milanesa de carne vacuna cubierta con salsa, queso fresco de vaca y cebolla caramelizada. Servida con papas rústicas o ensalada.",
    description:
      "Breaded beef topped with tomato sauce, fresh cow's milk cheese, and sweet caramelized onions. Served with rustic potatoes or a classic salad.",
    precio: 17000,
    vegetariano: false,
    sinTacc: false,
    onOff: null,
  },
  {
    id: 51,
    nombre: "Milanesa napolitana",
    categoria: "CARNES",
    descripcion:
      "Milanesa de carne vacuna cubierta con salsa de tomate, jamón y queso fresco de vaca. Acompañada de papas rústicas o ensalada clásica.",
    description:
      "Breaded beef topped with tomato sauce, ham, and fresh melted cheese. Served with rustic potatoes or a classic salad.",
    precio: 17000,
    vegetariano: false,
    sinTacc: false,
    onOff: null,
  },
  {
    id: 52,
    nombre: "Milanesa para dos personas",
    categoria: "CARNES",
    descripcion:
      "Milanesa XL de carne vacuna para dos personas. Puedes elegirla en cualquiera de nuestras variedades (Sola, Napolitana, Alemania, Fugazzeta o A Caballo). Con guarnición de papas rústicas o ensalada clásica.",
    description:
      "Extra-large breaded beef cutlet for two. Choose your style: Classic, Napolitana, Alemania, Fugazzeta, or A Caballo. Served with rustic potatoes or a classic salad.",
    precio: 28000,
    vegetariano: false,
    sinTacc: false,
    onOff: null,
  },
  {
    id: 53,
    nombre: "Ensalada clasica",
    categoria: "GUARNICION",
    descripcion:
      "Mix fresco de lechuga, tomate, zanahoria rallada y huevo.",
    description:
      "Crisp lettuce, tomato, grated carrot, and egg.",
    precio: 8000,
    vegetariano: true,
    sinTacc: true,
    onOff: null,
  },
  {
    id: 54,
    nombre: "Papas rusticas",
    categoria: "GUARNICION",
    descripcion:
      "Papas cortadas a mano en finas láminas y preparadas en el momento",
    description:
      "Thinly sliced potatoes, cut by hand and prepared to order.",
    precio: 8000,
    vegetariano: true,
    sinTacc: true,
    onOff: null,
  },
  {
    id: 56,
    nombre: "Ensalada calchaqui",
    categoria: "GUARNICION",
    descripcion:
      "Combinación de lechuga, tomate, zanahoria, remolacha, huevo y jamon con el toque regional de porotos pallares, habas, queso de cabra local y semillas de chía.",
    description:
      "Lettuce, tomato, carrot, beetroot, egg, and ham enhanced with regional butter beans, broad beans, local goat cheese, and chia seeds.",
    precio: 10000,
    vegetariano: false,
    sinTacc: true,
    onOff: null,
  },
  {
    id: 57,
    nombre: "Espaguettis de Maiz capia y pimenton",
    categoria: "PASTAS",
    descripcion:
      "Pasta artesanal elaborada por una cooperativa local con maíz capia regional. Una opción libre de gluten acompañada de nuestra salsa de tomate o boloñesa (carne y tomate).",
    description:
      "Artisan pasta crafted by a local cooperative using regional capia corn. A gluten-free option served with tomato or Bolognese sauce.",
    precio: 13500,
    vegetariano: true,
    sinTacc: true,
    onOff: null,
  },
  {
    id: 58,
    nombre: "Espaguettis de Maiz morado",
    categoria: "PASTAS",
    descripcion:
      "Pasta artesanal de color intenso y sabor ancestral, elaborada con maíz morado por cooperativas locales. Servidos con salsa de tomate o boloñesa.",
    description:
      "Ancestral purple corn pasta, handmade by local cooperatives, offering deep color and rich flavor. Served with tomato or Bolognese sauce.",
    precio: 13500,
    vegetariano: true,
    sinTacc: true,
    onOff: null,
  },
  {
    id: 59,
    nombre: "Tallarines al huevo",
    categoria: "PASTAS",
    descripcion:
      "Tallarines al huevo de elaboración propia, hechos con ingredientes frescos. Servidos con una salsa de tomate o boloñesa (carne y tomate).",
    description:
      "Freshly made egg pasta prepared in-house, served with tomato or Bolognese sauce.",
    precio: 14000,
    vegetariano: true,
    sinTacc: false,
    onOff: null,
  },
  {
    id: 62,
    nombre: "La colonial",
    categoria: "POSTRE",
    descripcion:
      "Una combinación clásica de nuestros cerros: queso de cabra artesanal acompañado de dulce de cayote, nueces seleccionadas, pasas de uva y un toque de miel.",
    description:
      "A classic pairing from our hills: artisan goat cheese served with cayote preserve, selected walnuts, raisins, and a drizzle of honey.",
    precio: 8000,
    vegetariano: false,
    sinTacc: false,
    onOff: null,
  },
];
